### ISSUE TITLE
Improve

### ISSUE THREAD

**Issue by sindresorhus** [ben-eb/gulp-symlink#15]
[gulp-sym](https://github.com/soyuka/gulp-sym) exists, but we prefer it to only be one symlink module. Can you and @soyuka work together please?

Here's are the arguments for gulp-sym existing: https://github.com/soyuka/gulp-sym#why

**Comment by SimenB** [comment]
Regarding Windows-support: Running ``npm test`` on Windows 8.1 fails 35 tests if not running as administrator. As administrator all is green.
Not sure if you can do anything about Windows' stupid permissions, though

**Comment by ben-eb** [comment]
@SimenB Thanks for the info! I'm planning to deprecate this module soon as gulp 4 has a new API for creating symlinks (`gulp.symlink`). That's not quite ready yet though. :smile:
