### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by rizalp** [ben-eb/gulp-symlink#19]
Hi there. I've been trying this plugin, and while it works as expected, I've some suggestion that I'd like to say.

I think it'd be more consistent with the way gulp API works if the plugin allows us to omit parameter. It will assume that we want to create streams of symlink. Then, we can pipe it to gulp.dest(), preserving the folder structure of source files.

For example, here's the source dirrectory: 

    $ tree source

    ├── fashion            
    │   ├── fashion (1).jpg
    │   ├── fashion (1).md 
    │   ├── fashion (2).jpg
    │   ├── fashion (2).md 
    │   ├── fashion (3).jpg
    │   └── fashion (3).md
    ├── logo keraton.PNG   
    └── vintage            
        ├── (1).jpg        
        ├── (1).md         
        ├── (2).jpg        
        ├── (2).md         
        ├── (3).jpg        
        └── (3).md         

These gulp task will output symlink streams to the destination: 

    gulp.task('photo', function(){
      var processedPhoto = gulp.src(['source/**/*.+(jpeg|jpg|png|gif)', '!' + 'source/logo keraton.PNG'], { base: 'source/' })
        .pipe(symlink())
        .pipe(gulp.dest('dist/'));
    });

The output folder, `dist/` will contain all generated symlink with preserved directory structure: 

     $ tree dist

    ├── fashion            
    │   ├── fashion (1).jpg@
    │   ├── fashion (2).jpg@
    │   ├── fashion (3).jpg@
    └── vintage            
        ├── (1).jpg@        
        ├── (2).jpg@        
        ├── (3).jpg@

**Comment by ben-eb** [comment]
This module has now been deprecated. https://github.com/ben-eb/gulp-symlink#deprecation-notice
