### ISSUE TITLE
Can not name a symlink with no extension

### ISSUE THREAD

**Issue by davemaurakis** [ben-eb/gulp-symlink#21]
I want to symlink a file and rename it without an extension...

``` javascript
gulp.task('default', function() {
  return gulp.src('.pre-commit')
    .pipe(symlink('.git/hooks/pre-commit'));
});
```

What I want: `.git/hooks/pre-commit -> ../../.pre-commit`
What I get: `.git/hooks/pre-commit/.pre-commit -> ../../../.pre-commit`

**Comment by gaowhen** [comment]
@ben-eb I use gulp-util 3.0.2 and get the error 

    fs.js:185
      binding.stat(pathModule._makeLong(path), cb);
          ^
    TypeError: path must be a string

**Comment by ben-eb** [comment]
@gaowhen See also: https://github.com/ben-eb/gulp-symlink/pull/22

**Comment by gaowhen** [comment]
@ben-eb thanks, #22 works.
