### ISSUE TITLE
EPERM error

### ISSUE THREAD

**Issue by gaowhen** [ben-eb/gulp-symlink#28]
hook.js

    var gulp = require('gulp');
    var symlink = require('gulp-symlink');

    function hook() {
      return gulp.src(['.precommit'])
        .pipe(symlink('.git/hooks/', {force: true}));
    }

    gulp.task('hook', hook);
    module.exports = hook;

error: 

    Message:
        EPERM, unlink '.git/hooks/'
    Details:
        errno: -1
        code: EPERM
        path: .git/hooks/

version

    "gulp": "^3.8.10",
    "gulp-symlink": "^2.1.0"

**Comment by ben-eb** [comment]
Try without the trailing slash; ./git/hooks

**Comment by gaowhen** [comment]
@ben-eb still the same error

**Comment by ben-eb** [comment]
From that error message, it looks like you don't have sufficient permissions to unlink your `.git/hooks` directory. It might be worth trying with the alternate method of returning a `symlink.File` object (https://github.com/ben-eb/gulp-symlink/issues/21)

**Comment by gaowhen** [comment]
yeah， #21  is useful, thanks.

**Comment by ben-eb** [comment]
Awesome. :smile:
