### ISSUE TITLE
Symlink is not cretated on windows (under non admin user)

### ISSUE THREAD

**Issue by operatino** [ben-eb/gulp-symlink#30]
Hi,

I faced an issue trying to run this plugin in Windows environment:

![image](http://d.pr/i/18SU3+)

Gulpfile.js:
```
var gulp = require('gulp');
var symlink = require('gulp-symlink');

gulp.task('link-project', function () {
    return gulp.src('../statics')
        .pipe(symlink('bundles/project'))
});
```

Spawned error is complaining about lacking permissions. This issue is solvable, and stable work-around could be fount in Bower utils https://github.com/bower/bower/blob/master/lib/util/createLink.js.

**Comment by ben-eb** [comment]
Just to note that this module is superfluous once symlinks land in gulp 4. I'm not sure when that will be, though. (https://github.com/ben-eb/gulp-symlink/issues/19)

A pull request for this would be appreciated & would need testing via something like appveyor.

**Comment by operatino** [comment]
Here you go #31 :)

**Comment by ben-eb** [comment]
Released as `2.1.1`. Thanks again for your contribution. :smile:

**Comment by operatino** [comment]
I tried to re-run tests on my virtual Windows machine, and they're still failing... It's because symlinks on windows work only with absolute paths:

```
gulp.task('link-project', function () {
    return gulp.src('../some/path')
        .pipe(symlink.absolute('bundles/project'))
});
```

Which means that with right configuration, module **will work** on Windows (thanks to recent fixes), but tests should be changed. You will need to check OS and run different tests, and most importantly - README should have info about those Windows specifics.

Seems like this Windows CI environment is not reliable, and not only because of symlinks. In my project I noticed that CI Windows has more stuff installed out-of-the box like libs for C++ compiling, which usually regular Windows user doesn't have.

Personally, I would do absolute links by default, just because they are working cross-platform.

**Comment by ben-eb** [comment]
I made relative symlinks the default behaviour as some builds are done in dev environments, then migrated to production; so it is possible that the directory structure changes. I don't think it is practical to change the default behaviour to be different depending on the operating system, so I think the best solution I can see is to have a note in the README about this limitation. What do you think?

At this point I don't want to invest a lot of time into reworking this module when I know gulp 4 is around the corner.
