### ISSUE TITLE
Package not working

### ISSUE THREAD

**Issue by apexskier** [ben-eb/gulp-symlink#35]
I've got version 2.1.3 installed, and it's not behaving like the docs at all. It's always creating a single file called the target (the [example](https://github.com/ben-eb/gulp-symlink#example) creates a symlink "build/videos -> ../../assets/some-large-video.mp4", then fails on the next pipe). Passing an array to symlink fails with an error telling me it expects a string.

**Comment by ben-eb** [comment]
What does your code look like? Last time I published this test still passed: https://github.com/ben-eb/gulp-symlink/blob/master/test/index.js#L211-L229

**Comment by ben-eb** [comment]
This module has now been deprecated. https://github.com/ben-eb/gulp-symlink#deprecation-notice
