### ISSUE TITLE
Symlink file into folder is not working

### ISSUE THREAD

**Issue by perrin4869** [ben-eb/gulp-symlink#36]
I made a simple repo showing the problem: https://github.com/perrin4869/gulp-symlink-problem
Basically, using `gulp.src` on a file and using `pipe` with `symlink("dirname")` gives the following error: 

```
Destination file exists (dest) - use force option to replace
```

**Comment by perrin4869** [comment]
The expected output is to have the file symlinked into the destination directory while preserving the original name

**Comment by ben-eb** [comment]
Does this work if you use the function instead?

```js
.pipe(symlink(function (file) {
  return path.join(file.base, 'dest', file.relative);
}));
```

**Comment by perrin4869** [comment]
yup, that's what I was using actually provisorily

**Comment by ben-eb** [comment]
Patches for this are welcome, however I'm looking to deprecate this module once gulp 4 is available; it comes with symlinks natively, which is a much better solution than this.

**Comment by perrin4869** [comment]
ok I see, then no point in patching it will wait for gulp 4 too then. Thanks!
