### ISSUE TITLE
Symlink group of files

### ISSUE THREAD

**Issue by admdh** [ben-eb/gulp-symlink#37]
Hi if i use this example:
```js
gulp.task('default', function () {
  return gulp.src('assets/video.mp4')
    .pipe(symlink('build/videos')) // Write to the destination folder
});
```
than symlink looks like this:
```
build/videos
```

but i would like to get 
```
build/videos/video.mp4
```

actually i would like to make symlinks for all files in folder to some destination so i could do something like this:

for this files i would like to create symlinks
```
src/a.file
src/b.file
src/c.file
```
and use something like this
```
gulp.task('default', function () {
  return gulp.src('src/*.file')
    .pipe(symlink('symlinkedfolder'))
});
```
and get this:
```
symlinkedfolder/a.file
symlinkedfolder/b.file
symlinkedfolder/c.file
```

is it possible or am i doing something wrong?

**Comment by ben-eb** [comment]
Possible duplicate: https://github.com/ben-eb/gulp-symlink/issues/19

gulp 4 has symlinking built in, so creating a stream of symlinks will be much easier then.

**Comment by admdh** [comment]
Thank you! is there any example?

**Comment by ben-eb** [comment]
API docs are here; https://github.com/gulpjs/vinyl-fs#symlinkfolder-options - not sure when gulp 4 will be released still, maybe @contra knows? :smile:

**Comment by contra** [comment]
You can require in the latest vinyl-fs right now, gulp 4 is coming soon

**Comment by ben-eb** [comment]
Just thinking it might be easier to deprecate this module for vinyl-fs instead.

**Comment by ben-eb** [comment]
This module has now been deprecated. https://github.com/ben-eb/gulp-symlink#deprecation-notice
