### ISSUE TITLE
gulp-symlink fails if source is itself a symlink

### ISSUE THREAD

**Issue by myitcv** [ben-eb/gulp-symlink#38]
Assume the following setup, where `app` is a symlink, and `dist` is a directory:

```
app -> /tmp/app
dist/
```

Then assume we write something like:

```
gulp.task("link", function() {
    return gulp.src("app")
    .pipe(symlink("dist/app", {force: true}));
});
```

fails with:

```
events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: EISDIR: illegal operation on a directory, read
    at Error (native)
```

Is it expected that a symlink source should work?

Thanks

**Comment by ben-eb** [comment]
It's probably worth looking to use vinyl symlinks instead of this module.

https://github.com/ben-eb/gulp-symlink/issues/37#issuecomment-173548509

**Comment by myitcv** [comment]
Thanks, works exactly as expected:

```javascript
var vfs = require('vinyl-fs');

gulp.task("link", function() {
  return vfs.src('app', {followSymlinks: false})
  .pipe(vfs.symlink('dist'));
});
```

**Comment by ben-eb** [comment]
You're welcome. Will see if I can find some time soon to update the documentation with that snippet and then deprecate this module. :+1:
